filetype plugin indent off
set runtimepath=/vimconfig/,/vimconfig/pack/plugins/start/*/,/usr/share/vim/vim82

filetype plugin indent on

let mapleader = ","

set nocompatible
set ai
set history=50
set ruler
set autoindent
set number
set dir=/tmp/
set autoread
set ut=100
set backspace=indent,eol,start
set undofile
set undodir=/tmp/
set undolevels=1000
set undoreload=10000
au CursorHold,CursorHoldI,FocusGained,BufEnter * checktime

syntax on

map Q gq

set suffixes+=.info,.aux,.log,.dvi,.bbl,.out,.o,.lo

syntax on

runtime! lightline.vim

map <leader>f :CtrlP<cr>
map <leader>s <Plug>CtrlSFPrompt

" The Silver Searcher
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
endif

" vim go
" disable open browser after posting snippet
let g:go_play_open_browser = 0
" enable goimports
let g:go_fmt_command = "goimports"
" enable additional highlighting
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
