set runtimepath=/vimconfig/,/vimconfig/pack/plugins/start/*/

let mapleader = ","

set nocompatible
set ai
set history=50
set ruler

map Q gq

set suffixes+=.info,.aux,.log,.dvi,.bbl,.out,.o,.lo

syntax on

runtime! lightline.vim

map <leader>f :CtrlP<cr>
map <leader>s <Plug>CtrlSFPrompt

" The Silver Searcher
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
endif
